#!/bin/sh
#
# Hook: pre-commit
# Desc: run tests on master branch

branch=$(git rev-parse --abbrev-ref HEAD)
exists=$(make -n precommit)

if [ "$branch" = "master" ] && [ "$exists" = 0 ]; then
  make precommit
fi